config/routes.rb
Sample::Application.routes.draw do
  
  authenticated :user do
    root to: "videos#index", :as => "userview"
  end

  authenticated :admin do
    root to: "admin_dashboards#index", :as => "adminview"
  end

  devise_for :users, :controllers => {registrations: 'users/registrations'}
  devise_for :admins
  
  resource 'admin_dashboards'
  resource 'videos'

  resource 'users'
  get "admin_dashboards/view" => "admin_dashboards#view"
  match "admin_dashboards/upload" => "admin_dashboards#upload",:via => :post
  
  

  root to: 'videos#index'
end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
	
	def generate_access_token
 	 	
 	 	begin
 	 		if (self.class.exists?(user_id: $id))
				a = self.class.where("user_id = ?", $id).first	 	   		
				a.access_token = SecureRandom.hex
				a.save!
	 	   	else
	 	   		self.class.create :access_token => SecureRandom.hex, :user_id => $id
 		   	end	
  		end while self.class.exists?(access_token: access_token)
	end

end

app/models/data_file.rb
class DataFile < ActiveRecord::Base
	def self.save(upload)
		name=upload['datafile']
		directory="public/video"
		path=File.join(directory, name)
		File.open(path, "wb"){ |f| f.write(upload['datafile'])}
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable, :authentication_keys => [:login]

 # attr_accessible :login
  attr_accessor :login

  validates :username,:uniqueness => {:case_sensitive => false }

  def self.find_first_by_auth_conditions(warden_conditions)
  conditions = warden_conditions.dup
  if login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  else
    where(conditions).first
  end
end
end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/Products_Controller.rb
class ProductsController < ApplicationController

before_filter :restrict_access

	private

	def restrict_access
  		authenticate_or_request_with_http_token do |token, options|
    		ApiKey.exists?(access_token: token)
  		end
	end

end

app/controllers/admin_dashboards_controller.rb
class AdminDashboardsController < ApplicationController

	before_action :authenticate_admin!, only: [:index, :update, :show]
  def index
  	@videos=Video.all
  end

  def update
    email=params[:email]
    type=params[:account_type]
    @user=User.find_by email:email
    @user.account_type=type
    if @user.save
      flash[:updated]="Account type updated successfully"
    end
      @users=User.all
    render "/admins/show"
  end

  def show
   	@users=User.all
  end

  def view
  end
  
  

  def upload
    post = DataFile.save(params[:upload])
    render :text => "File has been uploaded successfully"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  
  before_filter :authenticate_user!
  
  def new
  	super
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice]="you have signed up successfully"
      render "users/sessions/new"
    else
      render :action => :new
    end
  end

  def update
    super
  end

   private
    
    def user_params
      params.require(:user).permit(:firstname, :lastname, :username, :email, :password, :password_confirmation, :reset_password_sent_at, :remember_created_at, :sign_in_count, :current_sign_in_at, :last_sign_in_at, :current_sign_in_ip, :last_sign_in_ip)
    end
end 

app/controllers/videos_controller.rb
class VideosController < ApplicationController

	before_action :authenticate_user!, only: [:index]

	def index
		@current_user = current_user.email

		$id = (User.find_by email:@current_user).id
		ApiKey.new.generate_access_token

		@acc_type = (User.find_by email:@current_user).account_type

		if @acc_type == "Gold"
				@videos = Video.all
		elsif @acc_type == "Silver"
				@videos = Video.where.not(account_type: "Gold")
		else
				@videos = Video.where(account_type: "Free")
		end

		respond_to do |format|
	    format.html #{ render json: @videos.as_json(except: [:id, :created_at, :updated_at ]) }
	    #{ render json: @videos.as_json(only: [:url, :Account_type]) }# index.html.erb
	    # format.xml  { render xml: @videos}
	    # format.json { render json: @videos.as_json(only: [:url, :Account_type]) }
	    end
	end	

	def show
		@videos = Video.where(account_type: "Free")	
	end	

 end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin_dashboards/index.html.erb
<%= link_to 'Logout', destroy_admin_session_path, :method=>'delete' %>
<%=  link_to '<button type="button">UploadVideos</button>'.html_safe,  '/admin_dashboards/view' %>
<%=  link_to '<button type="button">ViewUsers</button>'.html_safe,  '/admin_dashboards' %>
<center>

<table>
<% @videos.each do |video| %>
<% @src = "//www.youtube.com/embed/"+"#{video.url.partition('=').last}"+"?feature=player_detailpage" %>
	<tr>
		<td><iframe width="500" height="250" src=<%=@src %> frameborder="0" allowfullscreen></iframe></td>
		<!--	<td><%= link_to video.url,video.url %></td>		-->
	</tr>	
<% end %>
</table>
</center>

app/views/admin_dashboards/show.html.erb
<center><h3>users</h3></center>
<% if !flash[:updated].nil? %>
 <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert" >×</button>
    <strong><%= flash[:updated] %></strong>
    </div>
<% end %>
<table border="1">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>LastName</th>
      <th>UserName</th>
      <th>Emailid</th>
      <th>AccountType</th>
    </tr>
  </thead>

   <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstname %></td>
        <td><%= user.lastname%></td>
        <td><%= user.username%></td>
        <td><%= user.email%></td>
        <td>
        <%= form_tag("/admins/update",:method=> "post") do %>
        <%= hidden_field_tag :email, user.email %>
        <%= user.account_type%><%= select_tag "account_type", "<option></option><option>Free</option><option>Silver</option><option>Gold</option>".html_safe , :onchange => "this.form.submit();"%>
        <%end%>
        </td>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin_dashboards/view.html.erb
<h1>File Upload</h1>
<%= form_tag(:action => "upload", :multipart => true, :method => "post") do %>
	
<p><label for="upload_file">Select File</label> : 
<%= file_field 'upload', 'datafile' %></p>



<%= submit_tag ("Upload") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<center><h3>videos</h3></center>
<div class="right">
	<%= @current_user %><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
</div>
<center>

<table>
<% @videos.each do |video| %>
<% @src = "//www.youtube.com/embed/"+"#{video.url.partition('=').last}"+"?feature=player_detailpage" %>
	<tr>
		<td><iframe width="500" height="250" src=<%=@src %> frameborder="0" allowfullscreen></iframe></td>
		<!--	<td><%= link_to video.url,video.url %></td>		-->
	</tr>	
<% end %>
</table>
</center>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<center>
	<h3>videos</h3>
	<%=  link_to '<button type="button">signin</button>'.html_safe,  '/users' %>
	<table>

		<% @videos.each do |video| %>
		<% @src = "//www.youtube.com/embed/"+"#{video.url.partition('=').last}"+"?feature=player_detailpage" %>
		  <tr>
			<td><iframe width="500" height="250" src=<%=@src %> frameborder="0" allowfullscreen></iframe></td>
			<!--	<td><%= link_to video.url,video.url %></td> 	-->
		  </tr>	
		<% end %>
	</table> 
</center>

app/views/videos/index.html.erb
<center><h3>videos</h3></center>
<div class="right">
	<%= @current_user %><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
</div>
<center>

<table>
<% @videos.each do |video| %>
<% @src = "//www.youtube.com/embed/"+"#{video.url.partition('=').last}"+"?feature=player_detailpage" %>
	<tr>
		<td><iframe width="500" height="250" src=<%=@src %> frameborder="0" allowfullscreen></iframe></td>
		<!--	<td><%= link_to video.url,video.url %></td>		-->
	</tr>	
<% end %>
</table>
</center>

app/views/videos/show.html.erb
<center>
	<h3>videos</h3>
	<%=  link_to '<button type="button">signin</button>'.html_safe,  '/users' %>
	<table>

		<% @videos.each do |video| %>
		<% @src = "//www.youtube.com/embed/"+"#{video.url.partition('=').last}"+"?feature=player_detailpage" %>
		  <tr>
			<td><iframe width="500" height="250" src=<%=@src %> frameborder="0" allowfullscreen></iframe></td>
			<!--	<td><%= link_to video.url,video.url %></td> 	-->
		  </tr>	
		<% end %>
	</table> 
</center>